from tkinter import *
from tkinter import messagebox
from PIL import ImageTk
import mysql.connector
db=mysql.connector.connect(host='localhost',user='root',password='Siva@123',database='userdata')
mycursor=db.cursor()
sql="INSERT INTO user(First_name,Last_name,Gender,State,District,School_name,10th_mark,12th_mark,Course,Dept,Duration,Fees,Phone_no)VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) "
class application:
    def greetings(self):
        self.greetingsframe=Frame(self.profileframe,height=580,width=720,bd=1,highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=75)
        self.frameimg=ImageTk.PhotoImage(file='C:/pictures/greetings720_580.jpg')
        self.labelig=Label(self.greetingsframe,image=self.frameimg).place(x=350,y=75)
        greetingslabel=Label(self.greetingsframe,text='Thankyou for your Submission',bg='white',fg='red',font=('helvatica',25)).place(x=500,y=300)
        contactlabel=Label(self.greetingsframe,text='We will contact soon!',fg='red',bg='white',font=('helvatica',25)).place(x=580,y=350)
    def profile(self):
        self.profileframe=Frame(self.courseframe,height=580,width=720,bd=1,bg='white',highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=75)
        self.details=Label(self.courseframe,text='PROFILE',font=('helvatica',30,'bold'),fg='red',bg='white').place(x=630,y=100)
        self.fdetails=Frame(self.courseframe,height=3,width=720,bg='whitesmoke').place(x=350,y=170)
        self.fname=Label(self.courseframe,text='First Name   :',font=('helvatica',18,'bold'),fg='red',bg='white').place(x=380,y=200)
        self.fnamee=Label(self.courseframe,textvariable=firstname,font=('helvatica',18),fg='darkblue',bg='white').place(x=550,y=200)
        self.lname=Label(self.courseframe,text='Last Name   :',font=('helvatica',18,'bold'),fg='red',bg='white').place(x=380,y=260)
        self.lnamee=Label(self.courseframe,textvariable=lastname,font=('helvatica',18),fg='darkblue',bg='white').place(x=550,y=260)
        self.gender=Label(self.courseframe,text='Gender        :',font=('helvatica',18,'bold'),fg='red',bg='white').place(x=380,y=320)
        self.phone=Label(self.courseframe,text='Phone no.    :',font=('helvatica',18,'bold'),fg='red',bg='white').place(x=380,y=380)
        self.phonee=Label(self.courseframe,textvariable=phoneno,font=('helvatica',18),fg='darkblue',bg='white').place(x=550,y=380)
        self.school=Label(self.courseframe,text='School         :',font=('helvatica',18,'bold'),fg='red',bg='white').place(x=380,y=440)
        self.schoole=Label(self.courseframe,textvariable=schoolname,font=('helvatica',18),fg='darkblue',bg='white').place(x=550,y=440)
        self.frame=Frame(self.courseframe,height=240,width=3,bg='whitesmoke').place(x=710,y=170)
        self.state=Label(self.courseframe,text='State          :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=750,y=200)
        self.statee=Label(self.courseframe,textvariable=state,fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=200)
        self.district=Label(self.courseframe,text='District        :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=750,y=260)
        self.districte=Label(self.courseframe,textvariable=district,fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=260)
        self.sslc=Label(self.courseframe,text='10th Mark   :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=750,y=320)
        self.sslce=Label(self.courseframe,textvariable=sslcmark,fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=320)
        self.hsc=Label(self.courseframe,text='12th Mark   :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=750,y=380)
        self.hsce=Label(self.courseframe,textvariable=hscmark,fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=380)
        self.course=Label(self.courseframe,text='Course         :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=380,y=500)
        self.dept=Label(self.courseframe,text='Department :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=750,y=500)
        self.duration=Label(self.courseframe,text='Duration       :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=380,y=560)
        self.fees=Label(self.courseframe,text='Fees            :',fg='red',bg='white',font=('helvatica',18,'bold')).place(x=750,y=560)
        self.framec=Frame(self.courseframe,height=100,width=3,bg='whitesmoke').place(x=710,y=500)
        profilebutton=Button(self.courseframe,text='Ok',bd=3,foreground='white',activeforeground='white',background='red',activebackground='red',font=('helvatica',13,'bold'),width=10,command=a.greetings).place(x=650,y=610)
    def enggsubmit(self):
        if engg.get()==1 and gender.get()==1:
            """
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","MECH","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            """
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MECH',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==1 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","MECH","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MECH',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==1 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","MECH","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MECH',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==2 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","ECE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='ECE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==2 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","ECE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='ECE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==2 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","ECE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='ECE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==3 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","EEE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='EEE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==3 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","EEE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='EEE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==3 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","EEE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='EEE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==4 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","CIVIL","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='CIVIL',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==4 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","CIVIL","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='CIVIL',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==4 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","CIVIL","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='CIVIL',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==5 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","CSE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='CSE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==5 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","CSE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='CSE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==5 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","CSE","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='CSE',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==6 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","IT","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='IT',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==6 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","IT","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='IT',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if engg.get()==6 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"Nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Engg","IT","4years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Enggineering',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='IT',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='4 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /year',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
    def artssubmit(self):
        if arts.get()==1 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","B.COM","3years","20,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='B.COM',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='20,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==1 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","B.COM","3years","20,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='B.COM',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='20,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==1 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","B.COM","3years","20,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='B.COM',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='20,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==2 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","M.COM","3years","20,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='M.COM',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='20,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==2 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","M.COM","3years","20,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='M.COM',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='20,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==2 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","M.COM","3years","20,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='M.COM',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='20,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==3 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","BBA","2years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='BBA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='2 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==3 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","BBA","2years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='BBA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='2 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==3 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nototsay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","BBA","2years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='BBA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='2 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==4 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","MBA","3years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MBA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='2 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==4 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","MBA","3years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MBA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='2 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==4 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","MBA","3years","50,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MBA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='2 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='50,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==5 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","BCA","3years","30,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='BCA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='30,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==5 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","BCA","3years","30,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='BCA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='30,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==5 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","BCA","3years","30,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='BCA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='30,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==6 and gender.get()==1:
            val=(firstname.get(),lastname.get(),"Male",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","MCA","3years","30,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Male',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MCA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='30,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==6 and gender.get()==2:
            val=(firstname.get(),lastname.get(),"Female",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","MCA","3years","30,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Female',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MCA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='30,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
        if arts.get()==6 and gender.get()==3:
            val=(firstname.get(),lastname.get(),"nottosay",state.get(),district.get(),schoolname.get(),sslcmark.get(),hscmark.get(),"Arts","MCA","3years","30,000",phoneno.get())
            mycursor.execute(sql,val)
            db.commit()
            messagebox.showinfo("Submit","Registration Successful.")
            a.profile()
            self.genderl=Label(self.courseframe,text='Others',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=320)
            self.coursel=Label(self.courseframe,text='Arts',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=500)
            self.deptl=Label(self.courseframe,text='MCA',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=500)
            self.durationl=Label(self.courseframe,text='3 years',fg='darkblue',bg='white',font=('helvatica',18)).place(x=550,y=560)
            self.feesl=Label(self.courseframe,text='30,000 /sem',fg='darkblue',bg='white',font=('helvatica',18)).place(x=920,y=560)
    def engg(self):
        self.enggframe=Frame(self.courseframe,height=465,width=720,bd=1,bg='white',highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=160)
        chooseengg=Label(self.enggframe,text='Choose Department',fg='red',bg='white',font=('helvatica',15,'bold')).place(x=400,y=190)
        self.mechframe=Frame(self.enggframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=230)
        self.eceframe=Frame(self.enggframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=230)
        self.eeeframe=Frame(self.enggframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=355)
        self.civilframe=Frame(self.enggframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=355)
        self.cseframe=Frame(self.enggframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=480)
        self.itframe=Frame(self.enggframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=480)
        self.mechrbutton=Radiobutton(self.mechframe,text='MECH',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=engg,value=1).place(x=450,y=240)
        self.mechdlabel=Label(self.mechframe,text='Duration : 4years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=270)
        self.mechflabel=Label(self.mechframe,text='Fees      : 50,000peryear',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=295)
        self.ecerbutton=Radiobutton(self.eceframe,text='ECE',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=engg,value=2).place(x=750,y=240)
        self.ecedlabel=Label(self.eceframe,text='Duration : 4years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=270)
        self.eceflabel=Label(self.eceframe,text='Fees      : 50,000peryear',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=295)
        self.eeerbutton=Radiobutton(self.eeeframe,text='EEE',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=engg,value=3).place(x=450,y=365)
        self.eeedlabel=Label(self.eeeframe,text='Duration : 4years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=395)
        self.eeeflabel=Label(self.eeeframe,text='Fees      : 50,000peryear',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=420)
        self.civilrbutton=Radiobutton(self.civilframe,text='CIVIL',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=engg,value=4).place(x=750,y=365)
        self.civildlabel=Label(self.civilframe,text='Duration : 4years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=395)
        self.civilflabel=Label(self.civilframe,text='Fees      : 50,000peryear',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=420)
        self.cserbutton=Radiobutton(self.cseframe,text='CSE',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=engg,value=5).place(x=450,y=490)
        self.csedlabel=Label(self.cseframe,text='Duration : 4years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=520)
        self.cseflabel=Label(self.cseframe,text='Fees      : 50,000peryear',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=545)
        self.itrbutton=Radiobutton(self.itframe,text='IT',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=engg,value=6).place(x=750,y=490)
        self.itdlabel=Label(self.itframe,text='Duration : 4years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=520)
        self.itflabel=Label(self.itframe,text='Fees      : 50,000peryear',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=545)
        enggbutton=Button(self.enggframe,text='submit',bd=3,foreground='white',activeforeground='white',background='red',activebackground='red',font=('helvatica',13,'bold'),width=10,command=a.enggsubmit).place(x=650,y=603)
    def arts(self):
        self.artsframe=Frame(self.courseframe,height=465,width=720,bd=1,bg='white',highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=160)
        choosearts=Label(self.artsframe,text='Choose Department',fg='red',bg='white',font=('helvatica',15,'bold')).place(x=400,y=190)
        self.bcomframe=Frame(self.artsframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=230)
        self.mcomframe=Frame(self.artsframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=230)
        self.bcaframe=Frame(self.artsframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=355)
        self.mcaframe=Frame(self.artsframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=355)
        self.bbaframe=Frame(self.artsframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=480)
        self.mbaframe=Frame(self.artsframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=480)
        self.bcomrbutton=Radiobutton(self.bcomframe,text='B.COM',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=1).place(x=450,y=240)
        self.bcomdlabel=Label(self.bcomframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=270)
        self.bcomflabel=Label(self.bcomframe,text='Fees      : 20,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=295)
        self.mcomrbutton=Radiobutton(self.mcomframe,text='M.COM',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=2).place(x=750,y=240)
        self.mcomdlabel=Label(self.mcomframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=270)
        self.mcomflabel=Label(self.mcomframe,text='Fees      : 20,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=295)
        self.bbarbutton=Radiobutton(self.bbaframe,text='BBA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=3).place(x=450,y=365)
        self.bbadlabel=Label(self.bbaframe,text='Duration : 2years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=395)
        self.bbaflabel=Label(self.bbaframe,text='Fees      : 50,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=420)
        self.mbarbutton=Radiobutton(self.mbaframe,text='MBA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=4).place(x=750,y=365)
        self.mbadlabel=Label(self.mbaframe,text='Duration : 2years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=395)
        self.mbaflabel=Label(self.mbaframe,text='Fees      : 50,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=420)
        self.bcarbutton=Radiobutton(self.bcaframe,text='BCA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=5).place(x=450,y=490)
        self.bcadlabel=Label(self.bcaframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=520)
        self.bcaflabel=Label(self.bcaframe,text='Fees      : 30,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=545)
        self.mcarbutton=Radiobutton(self.mcaframe,text='MCA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=6).place(x=750,y=490)
        self.mcadlabel=Label(self.mcaframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=520)
        self.mcaflabel=Label(self.mcaframe,text='Fees      : 30,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=545)
        artsbutton=Button(self.artsframe,text='submit',bd=3,foreground='white',activeforeground='white',background='red',activebackground='red',font=('helvatica',13,'bold'),width=10,command=a.artssubmit).place(x=650,y=603)
    def admission(self):
        if firstname.get()=='' or lastname.get()=='' or state.get()=='' or district.get()=='' or schoolname.get()=='' or phoneno.get()=='':
           messagebox.showerror('Error','All Fields are Required.')
        elif hscmark.get() <=600 and hscmark.get() >350:
            messagebox.showinfo('Information','Eligible for both Arts and engineering courses.')
            self.courseframe=Frame(userframe,height=550,width=720,bd=1,bg='white',highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=75)
            self.choicelabel=Label(self.courseframe,text='Choose Course   :',font=('helvatica',18,'bold'),fg='red',bg='white').place(x=450,y=100)
            courseheadframe=Frame(self.courseframe,height=3,width=720,bd=1,bg='white',highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=160)
            self.artsrbutton=Radiobutton(self.courseframe,text='Arts',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',variable=course,value=1,font=('helvatica',17),command=a.arts).place(x=700,y=100)
            self.enggrbutton=Radiobutton(self.courseframe,text='Engg',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',variable=course,value=2,font=('helvatica',17),command=a.engg).place(x=850,y=100)
        elif hscmark.get()<=350 and hscmark.get()>200:
            messagebox.showinfo('Information','Eligible for only Arts course.')
            self.coursesframe=Frame(userframe,height=550,width=720,bd=1,bg='white',highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=75)
            eligiblelabel=Label(self.coursesframe,text='You are eligible for only Arts course.',fg='darkblue',bg='white',font=('helvatica',18,'bold')).place(x=380,y=120)
            choosedept=Label(self.coursesframe,text='Choose Department',fg='darkblue',bg='white',font=('helvatica',15,'bold')).place(x=400,y=190)
            self.bcomframe=Frame(self.coursesframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=230)
            self.mcomframe=Frame(self.coursesframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=230)
            self.bcaframe=Frame(self.coursesframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=355)
            self.mcaframe=Frame(self.coursesframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=355)
            self.bbaframe=Frame(self.coursesframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=430,y=480)
            self.mbaframe=Frame(self.coursesframe,height=100,width=250,bd=1,relief='raised',bg='white').place(x=730,y=480)
            self.bcomrbutton=Radiobutton(self.bcomframe,text='B.COM',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=1).place(x=450,y=240)
            self.bcomdlabel=Label(self.bcomframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=270)
            self.bcomflabel=Label(self.bcomframe,text='Fees      : 20,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=295)
            self.mcomrbutton=Radiobutton(self.mcomframe,text='M.COM',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=2).place(x=750,y=240)
            self.mcomdlabel=Label(self.mcomframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=270)
            self.mcomflabel=Label(self.mcomframe,text='Fees      : 20,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=295)
            self.bbarbutton=Radiobutton(self.bbaframe,text='BBA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=3).place(x=450,y=365)
            self.bbadlabel=Label(self.bbaframe,text='Duration : 2years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=395)
            self.bbaflabel=Label(self.bbaframe,text='Fees      : 50,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=420)
            self.mbarbutton=Radiobutton(self.mbaframe,text='MBA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=4).place(x=750,y=365)
            self.mbadlabel=Label(self.mbaframe,text='Duration : 2years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=395)
            self.mbaflabel=Label(self.mbaframe,text='Fees      : 50,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=420)
            self.bcarbutton=Radiobutton(self.bcaframe,text='BCA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=5).place(x=450,y=490)
            self.bcadlabel=Label(self.bcaframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=520)
            self.bcaflabel=Label(self.bcaframe,text='Fees      : 30,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=470,y=545)
            self.mcarbutton=Radiobutton(self.mcaframe,text='MCA',fg='darkblue',bg='white',activeforeground='darkblue',activebackground='white',font=('helvatica',14),variable=arts,value=6).place(x=750,y=490)
            self.mcadlabel=Label(self.mcaframe,text='Duration : 3years',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=520)
            self.mcaflabel=Label(self.mcaframe,text='Fees      : 30,000persem',font=('helvatica',13),fg='darkblue',bg='white').place(x=770,y=545)
            artsbutton=Button(self.coursesframe,text='submit',bd=3,foreground='white',activeforeground='white',background='red',activebackground='red',font=('helvatica',13,'bold'),width=10,command=a.artssubmit).place(x=650,y=603)
a=application()
root=Tk()
phoneno=StringVar()
firstname=StringVar()
lastname=StringVar()
gender=IntVar()
gender.set(1)
state=StringVar()
district=StringVar()
schoolname=StringVar()
sslcmark=IntVar()
hscmark=IntVar()
course=IntVar()
engg=IntVar()
engg.set(1)
arts=IntVar()
arts.set(1)
logo=ImageTk.PhotoImage(file='C:/pictures/logo.ico')
root.iconphoto(False,logo)
root.geometry('1400x700')
root.title('Application Form...')
img=ImageTk.PhotoImage(file='C:/pictures/images_1400x700.jpeg')
imglabel=Label(root,image=img).place(x=0,y=0)
userframe=Frame(root,height=550,width=720,bd=1,bg='white',highlightthickness=1,highlightbackground='whitesmoke',relief='ridge').place(x=350,y=75)
imgframe=ImageTk.PhotoImage(file='C:/pictures/fbg70_70.jpg')
imglabel1=Label(userframe,image=imgframe).place(x=410,y=95)
headlabel=Label(userframe,text='SS College of Arts and Engineering,\nTrichy,Tamilnadu',font=('courier',18,'bold'),bg='white',fg='red').place(x=510,y=105)
headframe=Frame(userframe,height=3,width=700,bg='whitesmoke').place(x=350,y=185)
label=Label(userframe,text='Fill the all details...',font=('helvatica',15,'italic'),fg='red',bg='white').place(x=380,y=215)
phonelabel=Label(userframe,text='Phone no.  :',fg='red',bg='white',font=('helvatica',15)).place(x=730,y=215)
phoneentry=Entry(userframe,bd=0,fg='darkblue',bg='white',font=('helvatica',13),textvariable=phoneno).place(x=850,y=220)
phoneframe=Frame(userframe,height=3,width=185,bg='red').place(x=850,y=240)
firstnamelabel=Label(userframe,text='First name :',fg='red',bg='white',font=('helvatica',15)).place(x=380,y=270)
fnameentry=Entry(userframe,bd=0,fg='darkblue',bg='white',font=('helvatica',13),textvariable=firstname).place(x=500,y=275)
fnameframe=Frame(userframe,height=3,width=185,bg='red').place(x=500,y=295)
lastnamelabel=Label(userframe,text='Last name  :',fg='red',bg='white',font=('helvatica',15)).place(x=730,y=270)
lnameentry=Entry(userframe,bd=0,fg='darkblue',bg='white',font=('helvatica',13),textvariable=lastname).place(x=850,y=275)
lnameframe=Frame(userframe,height=3,width=185,bg='red').place(x=850,y=295)
genderlabel=Label(userframe,text='Gender      :',fg='red',bg='white',font=('helvatica',15)).place(x=380,y=330)
malerbutton=Radiobutton(userframe,text='Male',font=('helvatica',15),fg='darkblue',bg='white',activebackground='white',activeforeground='darkblue',variable=gender,value=1).place(x=500,y=330)
femalerbutton=Radiobutton(userframe,text='Female',font=('helvatica',15),fg='darkblue',bg='white',variable=gender,value=2,activebackground='white',activeforeground='darkblue').place(x=630,y=330)
othersrbutton=Radiobutton(userframe,text='Prefer not to say',font=('helvatica',15),fg='darkblue',bg='white',variable=gender,value=3,activebackground='white',activeforeground='darkblue').place(x=780,y=330)
Statelabel=Label(userframe,text='State         :',fg='red',bg='white',font=('helvatica',15)).place(x=380,y=390)
stateentry=Entry(userframe,bd=0,fg='darkblue',bg='white',font=('helvatica',13),textvariable=state).place(x=500,y=395)
stateframe=Frame(userframe,height=3,width=185,bg='red').place(x=500,y=415)
districtlabel=Label(userframe,text='District       :',fg='red',bg='white',font=('helvatica',15)).place(x=730,y=390)
districtentry=Entry(userframe,bd=0,fg='darkblue',bg='white',font=('helvatica',13),textvariable=district).place(x=850,y=395)
districtframe=Frame(userframe,height=3,width=185,bg='red').place(x=850,y=415)
schoolnamelabel=Label(userframe,text='School name :',fg='red',bg='white',font=('helvatica',15)).place(x=380,y=450)
schoolnameentry=Entry(userframe,bd=0,width=40,fg='darkblue',bg='white',font=('helvatica',13),textvariable=schoolname).place(x=530,y=455)
schoolnameframe=Frame(userframe,height=3,width=365,bg='red').place(x=530,y=475)
sslcmarklabel=Label(userframe,text='10th mark   :',fg='red',bg='white',font=('helvatica',15)).place(x=380,y=510)
sslcmarkentry=Entry(userframe,bd=0,fg='darkblue',bg='white',font=('helvatica',13),textvariable=sslcmark).place(x=500,y=515)
sslcmarkframe=Frame(userframe,height=3,width=185,bg='red').place(x=500,y=535)
hscmarklabel=Label(userframe,text='12th mark   :',fg='red',bg='white',font=('helvatica',15)).place(x=730,y=510)
hscmarkentry=Entry(userframe,bd=0,fg='darkblue',bg='white',font=('helvatica',13),textvariable=hscmark).place(x=850,y=515)
hscmarkframe=Frame(userframe,height=3,width=185,bg='red').place(x=850,y=535)
nextbutton=Button(userframe,text='Next',width=10,foreground='white',activeforeground='white',background='red',activebackground='red',font=('halvatica',13,'bold'),bd=3,command=a.admission).place(x=650,y=570)
root.mainloop()
